//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanEmeterio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color ColorFondoRombo {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoRombo"]));
            }
            set {
                this["ColorFondoRombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color ColorFondoChev {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoChev"]));
            }
            set {
                this["ColorFondoChev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorEtiquetaRombo {
            get {
                return ((global::System.Drawing.Color)(this["ColorEtiquetaRombo"]));
            }
            set {
                this["ColorEtiquetaRombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorEtiquetaChev {
            get {
                return ((global::System.Drawing.Color)(this["ColorEtiquetaChev"]));
            }
            set {
                this["ColorEtiquetaChev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorTextoRombo {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextoRombo"]));
            }
            set {
                this["ColorTextoRombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorTextoChev {
            get {
                return ((global::System.Drawing.Color)(this["ColorTextoChev"]));
            }
            set {
                this["ColorTextoChev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorFondoTextoRombo {
            get {
                return ((global::System.Drawing.Color)(this["ColorFondoTextoRombo"]));
            }
            set {
                this["ColorFondoTextoRombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color colorFondoTextoChev {
            get {
                return ((global::System.Drawing.Color)(this["colorFondoTextoChev"]));
            }
            set {
                this["colorFondoTextoChev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBotonRombo {
            get {
                return ((global::System.Drawing.Color)(this["ColorBotonRombo"]));
            }
            set {
                this["ColorBotonRombo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBotonChev {
            get {
                return ((global::System.Drawing.Color)(this["ColorBotonChev"]));
            }
            set {
                this["ColorBotonChev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int TamFuente {
            get {
                return ((int)(this["TamFuente"]));
            }
            set {
                this["TamFuente"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.0.10;user id=root;password=Mapuch33;defaultcommandtimeout=1000;per" +
            "sistsecurityinfo=True;database=sanemeterio")]
        public string Conex {
            get {
                return ((string)(this["Conex"]));
            }
        }
    }
}
